# coding: utf-8
defo = np.load('deformation.npy')
defo_img = latlon.LatlonImage(data=np.mean(defo[-3:], axis=0), dem_rsc_file='dem.rsc')
plotting.plot_image_shifted(defo_img, cmap='seismic', label='Centimeters', perform_shift=False)
plotting.plot_image_shifted(defo_img, cmap='discrete_seismic', label='Centimeters', perform_shift=False)
plotting.plot_image_shifted(defo_img, cmap='discrete_seismic5', label='Centimeters', perform_shift=False)
plotting.plot_image_shifted(defo_img, cmap='discrete_seismic7', label='Centimeters', perform_shift=False)
plt.savefig('defo_img_figure.png', bbox_inches='tight', transparent=True, dpi=300)
plotting.plot_image_shifted(defo_img, cmap='seismic', label='Centimeters', perform_shift=False)
plt.savefig('defo_img_figure_seismic.png', bbox_inches='tight', transparent=True, dpi=300)
plt.imshow(defo_img, cmap='seismic')
plt.imshow(defo_img, cmap='seismic', vmax=5, vmin=-5))
plt.imshow(defo_img, cmap='seismic', vmax=5, vmin=-5)
plt.imshow(defo_img, cmap='seismic', vmax=8, vmin=-8)
plt.axis('off')
plt.savefig('defo_img_noaxes_seismic.png', bbox_inches='tight', transparent=True, dpi=300)
plt.imshow(defo_img, cmap='discrete_seismic7')
plt.imshow(defo_img, cmap='discrete_seismic7', vmax=5, vmin=5)
plt.imshow(defo_img, cmap='discrete_seismic7', vmax=5, vmin=5)
plt.imshow(defo_img, cmap='discrete_seismic7', vmax=5, vmin=-5)
plt.axis('off')
plt.savefig('defo_img_noaxes_discrete_seismic.png', bbox_inches='tight', transparent=True, dpi=300)
defo2 = np.load('/data3/scott/pecos/path85stitch/igrams/deformation.npy')
geolist2 = np.load('/data3/scott/pecos/path85stitch/igrams/geolist.npy')
defo_img2 = latlon.LatlonImage(data=np.mean(defo[-3:], axis=0), dem_rsc_file='/data3/scott/pecos/path85stitch/igrams/dem.rsc')
defo_img2 = latlon.LatlonImage(data=np.mean(defo2[-3:], axis=0), dem_rsc_file='/data3/scott/pecos/path85stitch/igrams/dem.rsc')
plt.imshow(defo_img2)
plotting.plot_image_shifted(defo_img2, cmap='discrete_seismic7', label='Centimeters', perform_shift=False)
plt.imshow(defo_img2, cmap='discrete_seismic7', vmin=-15, vmax=5)
plt.imshow(defo_img2, cmap='discrete_seismic7', vmin=-7, vmax=7)
plt.colorbar()
plotting.plot_image_shifted(defo_img2, cmap='discrete_seismic7', label='Centimeters', perform_shift=True)
plotting.plot_image_shifted(defo_img2, cmap='discrete_seismic7', label='Centimeters', perform_shift=True)
plotting.plot_image_shifted(defo_img2, cmap='discrete_seismic7', label='Centimeters', perform_shift=True)
plt.savefig('defo_img_large_figure_discrete_seismic.png', bbox_inches='tight', transparent=True, dpi=300)
plotting.plot_image_shifted(defo_img2, cmap='discrete_seismic7', label='Centimeters', perform_shift=True, colorbar=False)
plt.axis('off')
plt.savefig('defo_img_large_noaxes_discrete_seismic.png', bbox_inches='tight', transparent=True, dpi=300)
