language: python
python:
  - "2.7"
  - "3.4"
cache: pip
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - python setup.py build_ext -i

script:
  nosetests -svd --with-doctest --with-coverage --cover-package=insar --where=insar

after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: always
