language: python
python:
  - "2.7"
  - "3.4"
cache: pip
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - python setup.py build_ext -i

# https://stackoverflow.com/a/35403128
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  nosetests -svd --with-doctest --with-coverage --cover-package=insar --where=insar

after_success: coveralls

notifications:
  email:
    on_success: never
    on_failure: always
