# Output directory holding all LOS and east/up solutions
project_out_directory = "/data6/scott/full_path151/7year_merged_solutions/"

# Common options to all LOS saving
[los]
# Output options:
outfile_template = "cumulative_los_path{path_num}_{dt}.tif"
freq = "1Y"
crs = "EPSG:4326"
out_directory_template = "los_path{path_num}"

# Figure saving
# figure_directory = "figures"
vm = 7  # Color limits (vmin, vmax) = (-vm, vm)
figsize = [8, 6]
defo_cmap = "seismic_wide_y_r"


# Path specific options

[paths.151.los]
directory = "/data6/scott/full_path151/igrams_looked_18/"
defo_filename = "deformation_elevation1.nc"
dset_name = "defo_lowess"
shifted_dset_name = "defo_lowess_shifted"
los_dset = "los_enu"
los_map_filename = "los_enu.tif"

# GPS comparison
gps_window_size = 9
# ref_station = None
gps_max_nan_pct = 0.7

# Masking
mask_filename = "masks.h5"
mask_missing_threshold = 8
cor_thresh = 0.11
max_abs_val_masking = 2

# deramping
do_final_deramp = true
deramp_order = 2

[paths.151.decomp]
# Position from west to east
position = 0
direction = "ascending"
# [path151.merging]
# overlaps_with = 85 #... do i want to do it this way?


[paths.85.los]
directory = "/data4/scott/path85/stitched/igrams_looked_18/"
# defo_filename = "deformation_elevation1.nc"
defo_filename = "deformation_elevation0.nc"
dset_name = "defo_lowess"
shifted_dset_name = "defo_lowess_shifted"
los_dset = "los_enu"
los_map_filename = "los_enu.tif"

# GPS comparison
gps_window_size = 9
ref_station = "TXKM"
gps_max_nan_pct = 0.7

# Masking
mask_filename = "masks.h5"
mask_missing_threshold = 8
cor_thresh = 0.11
max_abs_val_masking = 2

# deramping
do_final_deramp = true
deramp_order = 2

[paths.85.decomp]
# Position from west to east
position = 1
direction = "descending"


[paths.78.los]
directory = "/data1/scott/pecos/path78-bbox2/igrams_looked_18/"
defo_filename = "deformation_elevation1.nc"
dset_name = "defo_lowess"
shifted_dset_name = "defo_lowess_shifted"
los_dset = "los_enu"
los_map_filename = "los_enu.tif"

# GPS comparison
gps_window_size = 9
ref_station = "TXKM"
gps_max_nan_pct = 0.5

# Masking
mask_filename = "masks.h5"
mask_missing_threshold = 8
cor_thresh = 0.11
max_abs_val_masking = 2

# deramping
do_final_deramp = true
deramp_order = 2

[paths.78.decomp]
# Position from west to east
position = 2
direction = "ascending"

[decomp.common]
outfile_template = "cumulative_east_up_paths_{asc_path_num}_{desc_path_num}_{dt}.tif"
los_map_filename = "los_enu.tif"
out_directory_template = "decomp_paths_{asc_path_num}_{desc_path_num}"

[decomp.1]
# TODO: get these from the previous config
# asc_directory: str
# desc_directory: str
asc_path_num = 151
desc_path_num = 85
# out_directory = 
# infile_glob = "cumulative_los_*.tif"

[decomp.2]
asc_path_num = 78
desc_path_num = 85
# out_directory = 
# infile_glob = "cumulative_los_*.tif"


[merger]
east_template = "merged_east_{date}.tif"
up_template = "merged_vertical_{date}.tif"
out_directory = "merged_cumulative_east_up"

[diff]
outfile_template = "merged_vertical_diff_{d1}_{d2}.tif"
out_directory = "merged_diffs_east_up"
skip_intervals = [1, 2]